name: mapbox_gl
description: A Flutter plugin for integrating Mapbox Maps inside a Flutter application on Android, iOS and web platfroms.
version: 0.16.0
homepage: https://github.com/tobrun/flutter-mapbox-gl

dependencies:
  flutter:
    sdk: flutter
  mapbox_gl_platform_interface:
    path: mapbox_gl_platform_interface
  mapbox_gl_web:
    path: mapbox_gl_web
  collection: ^1.15.0

dev_dependencies:
  mustache_template: ^2.0.0
  recase: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mapbox.mapboxgl
        pluginClass: MapboxMapsPlugin
      ios:
        pluginClass: MapboxMapsPlugin
      web:
        default_package: mapbox_gl_web

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.10.0"
